### ISSUE TITLE
bad management of service plan

### ISSUE THREAD

**Issue by jigeay** [gomorpheus/terraform-provider-morpheus#209] opened 2024-02-08 16:11 UTC
Hello, 
With this code : 

`data "morpheus_price_set" "resource_price_set" {
  name = "Default Price Set"
}

resource "morpheus_service_plan" "vmware" {
  for_each       = var.vmware_plans
  name           = each.key
  code           = each.key
  active         = true
  provision_type = "vmware"
  // Processors
  max_cores        = each.value["cpu"]
  custom_cores     = false
  cores_per_socket = 1

  // Memory
  max_memory       = each.value["ram"]
  memory_size_type = "mb"
  custom_memory    = false

  //Storage
  max_storage             = 0
  storage_size_type       = "gb"
  customize_root_volume   = true
  customize_extra_volumes = true
  add_volumes             = true
  price_set_ids = [data.morpheus_price_set.resource_price_set.id]
}`

it applies well and creates a service plan : 
![image](https://github.com/gomorpheus/terraform-provider-morpheus/assets/30889106/24ee79db-0c29-4a38-a258-2ac954594206)
but when i try to use it in a working catalog, it does : 
![image](https://github.com/gomorpheus/terraform-provider-morpheus/assets/30889106/52293c03-4532-48ad-a92a-c3214c1a8a0a)

If i get back to the ui, open the plan, and hit save, when i get back to the catalog : it works correctly.

Can you have a look on that ?

regards,

Matthieu

**Comment by martezr** [comment] 2024-02-08 22:30
The cause of the issue is that the UI displays a value of 0 in the field but actually passes a null value to the system. The provider code has been updated to accommodate this by passing a null value if the max_disks_allowed is set to 0 or not defined. The fix will be available in the next release of the provider. A workaround in the interim is to define a non-zero value that is high enough that it is unlikely to be reached.

**Comment by jigeay** [comment] 2024-02-09 11:39
thank you for the workaround : i will definitively do that 👍

**Comment by martezr** [comment] 2024-04-24 19:20
This has been fixed in the latest release of the Terraform provider (v0.9.9)

**Closed by martezr** 2024-04-24 19:20 UTC
Labels: bug
