### ISSUE TITLE
`morpheus_workflow_catalog_item`, `morpheus_instance_catalog_item` - logo triggers change on each plan/apply

### ISSUE THREAD

**Issue by mbjorgan** [gomorpheus/terraform-provider-morpheus#146] opened 2023-08-09 08:45 UTC
When setting logo/image path on `morpheus_workflow_catalog_item` and `morpheus_instance_catalog_item` we have a folder containing the images (since we're not using one of the logos that comes with Morpheus), and we reference them in the catalog items.

On each plan/apply terraform wants to change. Any workaround on this or a fix needs to be implemented?

**Comment by mbjorgan** [comment] 2023-09-19 06:53
Any progress on this?

**Comment by martezr** [comment] 2023-09-19 21:13
I should be able to dig into this issue on this week and if a code change is necessary it would likely be part of a release that's pushed sometime next week.

**Comment by martezr** [comment] 2023-09-22 16:22
This issue has been identified to have been caused by the provider not properly supporting the use of sourcing the image from a subdirectory. The lookup to add the image works fine but when the provider sets the state it improperly sets the name of the image to the path attribute instead of just the image name. A workaround until a new release is created would be to move the images into the working directory of the Terraform code. The following PR fixed the issue and will likely be released next week - https://github.com/gomorpheus/terraform-provider-morpheus/pull/153

**Comment by martezr** [comment] 2023-10-06 14:52
This issue has been resolved in the v0.9.5 release of the Terraform provider.

**Closed by martezr** 2023-10-06 14:52 UTC
Labels: bug
